"""IDQN training/eval at one explicit floor, reduced to delay-per-completed-trip
and paired against both analysis/corridor_sweep.csv's green_wave rows and
analysis/ippo_sweep_peak_100k_check.csv's matched-100k-budget ippo rows.

Same methodology as analysis/ippo_sweep.py (tripinfo reduction, seed set
42-51, resumable "reuse what's on disk" design) applied to the true-
independent DQN driver (train_corridor_dqn.py) instead of the parameter-
shared IPPO one.

    python -m analysis.idqn_sweep --scenario corridor_peak --min-green 10 \
        --seeds 42 43 44 --lam 0.5 --steps 100000

IMPORTANT: this script's own IDQN sweep and its two reference CSVs must be
trained at the *same* step budget to be comparable. analysis/ippo_sweep.csv
holds SP4's 16k-step IPPO data (a much smaller training budget) --
analysis/ippo_sweep_peak_100k_check.csv holds the matched 100k-step data
real SP5 runs (steps=100000, this script's default) should pair against.
load_ippo_bar defaults to the 100k file for that reason; paired_vs's caller
in __main__ also runs a cheap wall_s-ratio guard (budget_gap) that would
have caught this pairing being run against the wrong file.
"""
import argparse
import os
import sys
import time
from typing import Optional

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)
os.chdir(REPO)

import pandas as pd

import train_corridor_dqn as tcd
from analysis.tripinfo import reduce_tripinfo
from env_common import CORRIDOR_SCENARIOS, tripinfo_path

OUT_CSV = os.path.join(REPO, "analysis", "idqn_sweep.csv")
CORRIDOR_SWEEP_CSV = os.path.join(REPO, "analysis", "corridor_sweep.csv")
# SP4's original 16k-step IPPO sweep. Still valid for a 16k-budget
# comparison, but NOT what a 100k-step IDQN run should be paired against --
# see load_ippo_bar and IPPO_SWEEP_100K_CSV below.
IPPO_SWEEP_CSV = os.path.join(REPO, "analysis", "ippo_sweep.csv")
# SP4's IPPO sweep re-run at 100k steps -- the matched-budget reference this
# script's default (steps=100000) IDQN runs should pair against. See
# docs/FINDINGS_2026-08-18-sp4-ippo-vs-corrected-bar.md's "100k" column.
IPPO_SWEEP_100K_CSV = os.path.join(REPO, "analysis", "ippo_sweep_peak_100k_check.csv")

os.environ.setdefault("TIME_TO_TELEPORT", "300")

# same survivorship-bias tolerance as ippo_sweep.COMPLETION_TOLERANCE /
# corridor_sweep.COMPLETION_TOLERANCE: two controllers whose completed-trip
# counts differ by more than this at the same floor are not being ranked on
# the same population of vehicles
COMPLETION_TOLERANCE = 0.02

# a cheap proxy for "are these two arms trained at the same step budget?".
# Neither reference CSV tracks a `steps` column (idqn_sweep.csv itself now
# does, see run_one/sweep below, but corridor_sweep.csv and the ippo CSVs
# don't), so wall_s -- which scales roughly with training steps -- is the
# best available signal. This tolerance is deliberately loose: it's meant to
# catch gross budget mismatches (e.g. 16k vs 100k, the bug that produced this
# project's SP5 headline miscomparison), not flag ordinary run-to-run noise.
BUDGET_RATIO_TOLERANCE = 2.0


def run_one(scenario: str, seed: int, min_green: int, lam: float, steps: int,
           force: bool = False) -> dict:
    """Train (if any of the 3 agent checkpoints is missing) + eval one seed,
    reduced to the ranking metric. Resumable: existing model checkpoints are
    reused when present; tripinfo is regenerated by evaluate() on every call
    regardless."""
    paths = [tcd._model_path(a, scenario, lam, seed, min_green, steps)
             for a in tcd.CORRIDOR_TS_IDS]
    if force or not all(os.path.exists(p) for p in paths):
        t0 = time.monotonic()
        tcd.train(scenario, lam, seed, steps, min_green)
        took = time.monotonic() - t0
    else:
        took = float("nan")
    tcd.evaluate(scenario, lam, seed, min_green, steps, tripinfo=True)
    trip = tripinfo_path(f"logs/eval_idqn_{tcd._tag(scenario, lam, seed, min_green, steps)}")
    row = reduce_tripinfo(trip)
    return {
        "controller": "idqn", "scenario": scenario, "seed": seed,
        "min_green": min_green, "delay_per_trip": row["trip_time_loss_mean"],
        "trips": row["trips_completed"], "wall_s": took, "steps": steps,
    }


def sweep(scenario: str, seeds, min_green: int, lam: float, steps: int,
         force: bool = False) -> pd.DataFrame:
    rows = []
    for seed in seeds:
        rows.append(run_one(scenario, seed, min_green, lam, steps, force))
        r = rows[-1]
        took = "reused" if pd.isna(r["wall_s"]) else f"{r['wall_s']:.0f}s"
        print(f"[{len(rows)}/{len(seeds)}] idqn seed{seed} "
              f"delay/trip={r['delay_per_trip']:7.1f}s trips={r['trips']:5d}  ({took})",
              flush=True)
    return pd.DataFrame(rows)


def paired_vs(idqn_df: pd.DataFrame, bar_df: pd.DataFrame, bar_name: str) -> dict:
    """idqn - bar_df per seed, paired. Both dataframes must be one (scenario,
    min_green) already -- raises if they disagree, the same cross-scenario
    guard ippo_sweep.paired_vs_green_wave relies on. bar_name labels which
    reference (green_wave / ippo) this call compares against."""
    i_scen = set(idqn_df["scenario"])
    b_scen = set(bar_df["scenario"])
    if i_scen != b_scen or len(i_scen) != 1:
        raise ValueError(f"scenario mismatch: idqn={i_scen} {bar_name}={b_scen}")
    wide = pd.merge(
        idqn_df[["seed", "delay_per_trip"]].rename(columns={"delay_per_trip": "idqn"}),
        bar_df[["seed", "delay_per_trip"]].rename(columns={"delay_per_trip": bar_name}),
        on="seed", how="inner")
    d = wide["idqn"] - wide[bar_name]
    return {
        "scenario": idqn_df["scenario"].iloc[0], "vs": bar_name,
        "mean": float(d.mean()),
        "sd": float(d.std(ddof=1)) if len(d) > 1 else float("nan"),
        "wins": int((d < 0).sum()), "n": int(len(d)),
    }


def completion_gap(idqn_df: pd.DataFrame, bar_df: pd.DataFrame, bar_name: str,
                   tolerance: float = COMPLETION_TOLERANCE) -> Optional[dict]:
    """Survivorship guard for the idqn/bar pairing -- ported from
    ippo_sweep.completion_gap (see that docstring for the full rationale),
    adapted to paired_vs's (idqn_df, bar_df, bar_name) shape so it works for
    both this script's pairings (green_wave and ippo).

    delay_per_trip is delay per COMPLETED trip. A controller that jams an
    approach until hundreds of vehicles never finish is scored on the
    survivors and can look better than one that cleared everybody. Returns
    None if mean trips completed are within `tolerance` of each other, else
    a dict describing the spread.
    """
    i_scen = set(idqn_df["scenario"])
    b_scen = set(bar_df["scenario"])
    if i_scen != b_scen or len(i_scen) != 1:
        raise ValueError(f"scenario mismatch: idqn={i_scen} {bar_name}={b_scen}")
    trips = {
        "idqn": float(idqn_df["trips"].mean()),
        bar_name: float(bar_df["trips"].mean()),
    }
    hi = max(trips.values())
    if hi <= 0:
        return None
    spread = (hi - min(trips.values())) / hi
    if spread <= tolerance:
        return None
    return {
        "scenario": idqn_df["scenario"].iloc[0], "vs": bar_name,
        "spread": spread, "trips": trips,
    }


def budget_gap(idqn_df: pd.DataFrame, bar_df: pd.DataFrame, bar_name: str,
              tolerance: float = BUDGET_RATIO_TOLERANCE) -> Optional[dict]:
    """Budget-mismatch guard: a cheap proxy for "were these two arms trained
    at comparable step budgets?", using mean wall_s as the signal since
    neither reference CSV tracks a `steps` column. Returns None if the two
    arms' mean wall_s are within `tolerance`x of each other, else a dict
    describing the ratio.

    This is exactly the check that would have caught SP5's original bug:
    pairing a 100k-step IDQN sweep (wall_s ~4200s/seed) against SP4's 16k-
    step analysis/ippo_sweep.csv (wall_s ~700-1100s/seed) -- a >4x gap.
    """
    idqn_wall = float(idqn_df["wall_s"].mean())
    bar_wall = float(bar_df["wall_s"].mean())
    if pd.isna(idqn_wall) or pd.isna(bar_wall) or idqn_wall <= 0 or bar_wall <= 0:
        return None
    ratio = max(idqn_wall, bar_wall) / min(idqn_wall, bar_wall)
    if ratio <= tolerance:
        return None
    return {
        "vs": bar_name, "ratio": ratio,
        "idqn_wall_s": idqn_wall, f"{bar_name}_wall_s": bar_wall,
    }


def load_green_wave_bar(scenario: str, min_green: int) -> pd.DataFrame:
    """green_wave rows already in analysis/corridor_sweep.csv for this
    (scenario, min_green)."""
    df = pd.read_csv(CORRIDOR_SWEEP_CSV)
    return df[(df["controller"] == "green_wave") & (df["scenario"] == scenario) &
              (df["min_green"] == min_green)]


def load_ippo_bar(scenario: str, min_green: int,
                  ippo_csv: str = IPPO_SWEEP_100K_CSV) -> pd.DataFrame:
    """ippo rows already in `ippo_csv` for this (scenario, min_green) --
    SP4's result, the second reference this sweep pairs against. Defaults to
    IPPO_SWEEP_100K_CSV (analysis/ippo_sweep_peak_100k_check.csv), the
    matched-100k-budget data real SP5 runs should compare against. Pass
    ippo_csv=IPPO_SWEEP_CSV explicitly for a 16k-budget comparison instead --
    but note budget_gap will (correctly) warn loudly if you then pair it
    against a 100k-step idqn_sweep.csv run."""
    df = pd.read_csv(ippo_csv)
    return df[(df["controller"] == "ippo") & (df["scenario"] == scenario) &
              (df["min_green"] == min_green)]


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--scenario", required=True, choices=list(CORRIDOR_SCENARIOS))
    p.add_argument("--min-green", type=int, required=True)
    p.add_argument("--lam", type=float, default=0.5)
    p.add_argument("--steps", type=int, default=100_000)
    p.add_argument("--seeds", type=int, nargs="+",
                   default=[42, 43, 44, 45, 46, 47, 48, 49, 50, 51])
    p.add_argument("--force", action="store_true")
    args = p.parse_args()
    if not os.environ.get("SUMO_HOME"):
        raise SystemExit("SUMO_HOME not set")

    df = sweep(args.scenario, args.seeds, args.min_green, args.lam, args.steps, args.force)
    if os.path.exists(OUT_CSV):
        prior = pd.read_csv(OUT_CSV)
        df = pd.concat([prior, df]).drop_duplicates(
            subset=["scenario", "seed", "min_green"], keep="last")
    df.to_csv(OUT_CSV, index=False)

    this_run = df[(df["scenario"] == args.scenario) & (df["min_green"] == args.min_green)]

    gw_bar = load_green_wave_bar(args.scenario, args.min_green)
    if gw_bar.empty:
        print(f"no green_wave rows in {CORRIDOR_SWEEP_CSV} for "
              f"{args.scenario}/mg{args.min_green} -- cannot pair")
    else:
        result = paired_vs(this_run, gw_bar, "green_wave")
        print(f"\nidqn - green_wave, {args.scenario} mg{args.min_green}: "
              f"{result['mean']:+.2f} +/- {result['sd']:.2f} s, "
              f"idqn wins {result['wins']}/{result['n']}")

        gap = completion_gap(this_run, gw_bar, "green_wave")
        if gap is not None:
            counts = "  ".join(f"{c}={n:.0f}" for c, n in gap["trips"].items())
            print(f"\n!!! survivorship warning: idqn and green_wave completed "
                  f"different numbers of trips at this floor.")
            print(f"    delay per COMPLETED trip favours whoever finished fewer "
                  f"of them.")
            print(f"    {gap['spread'] * 100:.1f}% spread   {counts}")

        bgap = budget_gap(this_run, gw_bar, "green_wave")
        if bgap is not None:
            print(f"\n!!! budget warning: idqn and green_wave have wall_s "
                  f"differing by {bgap['ratio']:.1f}x -- are you comparing "
                  f"matched training budgets?")

    ippo_bar = load_ippo_bar(args.scenario, args.min_green)
    if ippo_bar.empty:
        print(f"no ippo rows in {IPPO_SWEEP_100K_CSV} for "
              f"{args.scenario}/mg{args.min_green} -- cannot pair")
    else:
        result = paired_vs(this_run, ippo_bar, "ippo")
        print(f"idqn - ippo, {args.scenario} mg{args.min_green}: "
              f"{result['mean']:+.2f} +/- {result['sd']:.2f} s, "
              f"idqn wins {result['wins']}/{result['n']}")

        gap = completion_gap(this_run, ippo_bar, "ippo")
        if gap is not None:
            counts = "  ".join(f"{c}={n:.0f}" for c, n in gap["trips"].items())
            print(f"\n!!! survivorship warning: idqn and ippo completed "
                  f"different numbers of trips at this floor.")
            print(f"    delay per COMPLETED trip favours whoever finished fewer "
                  f"of them.")
            print(f"    {gap['spread'] * 100:.1f}% spread   {counts}")

        bgap = budget_gap(this_run, ippo_bar, "ippo")
        if bgap is not None:
            print(f"\n!!! budget warning: idqn and ippo have wall_s differing "
                  f"by {bgap['ratio']:.1f}x -- are you comparing matched "
                  f"training budgets?")
